'use server';
/**
 * @fileOverview A Genkit flow for generating SEO-optimized website content and structure based on a given topic.
 *
 * - generateSiteContentAndStructure - A function that orchestrates the generation of site content and structure.
 * - GenerateSiteContentAndStructureInput - The input type for the generateSiteContentAndStructure function.
 * - GenerateSiteContentAndStructureOutput - The return type for the generateSiteContentAndStructure function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSiteContentAndStructureInputSchema = z.object({
  topic: z
    .string()
    .describe('The main topic for the pSEO site, e.g., "Children\'s Day event venues"'),
  requirements: z
    .string()
    .optional()
    .describe(
      'Additional SEO requirements or keywords, e.g., "family-friendly, outdoor activities, Seoul"'
    ),
});
export type GenerateSiteContentAndStructureInput = z.infer<
  typeof GenerateSiteContentAndStructureInputSchema
>;

const PageSchema = z.object({
  slug: z
    .string()
    .describe('The URL slug for the page (e.g., "about-us"). Must be kebab-case.'),
  title: z.string().describe('The HTML <title> for the page, optimized for SEO.'),
  metaDescription: z
    .string()
    .describe('The meta description for this specific page, optimized for SEO.'),
  h1: z.string().describe('The main H1 heading for the page content.'),
  bodyContent: z
    .array(z.string())
    .describe('An array of paragraphs (strings) for the page body content.'),
  keywords: z
    .array(z.string())
    .describe('A list of 3-5 relevant keywords for this page, optimized for SEO.'),
});

const GenerateSiteContentAndStructureOutputSchema = z.object({
  siteTitle: z.string().describe('The main title for the entire website.'),
  metaDescription: z
    .string()
    .describe('A global meta description for the website, optimized for SEO.'),
  pages: z
    .array(PageSchema)
    .describe('An array of page objects, each containing content and metadata.'),
});
export type GenerateSiteContentAndStructureOutput = z.infer<
  typeof GenerateSiteContentAndStructureOutputSchema
>;

export async function generateSiteContentAndStructure(
  input: GenerateSiteContentAndStructureInput
): Promise<GenerateSiteContentAndStructureOutput> {
  return generateSiteContentAndStructureFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSiteContentAndStructurePrompt',
  input: {schema: GenerateSiteContentAndStructureInputSchema},
  output: {schema: GenerateSiteContentAndStructureOutputSchema},
  // Using gemini-1.5-flash as the model for content generation since Claude API is not configured.
  model: 'gemini-1.5-flash',
  prompt: `You are an expert SEO content strategist and website architect. Your task is to generate a comprehensive, multi-page website structure and all necessary SEO-optimized content based on a given topic.\n\nYou need to create a site title, a global meta description, and then a list of individual pages. Each page must have a unique URL slug (kebab-case), an SEO-optimized title, a meta description, a main H1 heading, and several paragraphs of body content. Also, include 3-5 highly relevant keywords for each page to ensure maximum SEO effectiveness.\n\nThe generated content must be highly relevant, engaging, and structured to rank well on search engines. Ensure that the tone is professional and informative, unless otherwise specified.\n\nTopic for the pSEO site: {{{topic}}}\n{{#if requirements}}\nAdditional SEO requirements or keywords: {{{requirements}}}\n{{/if}}\n\nPlease structure your output strictly as a JSON object matching the defined schema.\n`,
});

const generateSiteContentAndStructureFlow = ai.defineFlow(
  {
    name: 'generateSiteContentAndStructureFlow',
    inputSchema: GenerateSiteContentAndStructureInputSchema,
    outputSchema: GenerateSiteContentAndStructureOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    if (!output) {
      throw new Error('No output generated by the AI.');
    }
    return output;
  }
);
